packages:
  - apps/*
  - packages/*

catalog:
  "@effect/language-service": 0.86.2
  "@effect/tsgo": 0.15.0
  "@types/node": 24.13.2
  "@typescript/native-preview": 7.0.0-dev.20260701.1
  effect: 4.0.0-beta.92
  typescript: 6.0.3
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: 4.1.9
  vite-plus: latest
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
minimumReleaseAge: 0
allowBuilds:
  electron: true
  esbuild: true
  msgpackr-extract: true
