/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedStorageRouteImport } from './routes/_authenticated/storage'
import { Route as AuthenticatedSnippetsRouteImport } from './routes/_authenticated/snippets'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as ApiAuthSignInRouteImport } from './routes/api/auth/sign-in'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStorageRoute = AuthenticatedStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSnippetsRoute = AuthenticatedSnippetsRouteImport.update({
  id: '/snippets',
  path: '/snippets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiAuthSignInRoute = ApiAuthSignInRouteImport.update({
  id: '/api/auth/sign-in',
  path: '/api/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/snippets': typeof AuthenticatedSnippetsRoute
  '/storage': typeof AuthenticatedStorageRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/snippets': typeof AuthenticatedSnippetsRoute
  '/storage': typeof AuthenticatedStorageRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/snippets': typeof AuthenticatedSnippetsRoute
  '/_authenticated/storage': typeof AuthenticatedStorageRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/billing'
    | '/settings'
    | '/snippets'
    | '/storage'
    | '/api/auth/callback'
    | '/api/auth/sign-in'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/billing'
    | '/settings'
    | '/snippets'
    | '/storage'
    | '/api/auth/callback'
    | '/api/auth/sign-in'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/billing'
    | '/_authenticated/settings'
    | '/_authenticated/snippets'
    | '/_authenticated/storage'
    | '/api/auth/callback'
    | '/api/auth/sign-in'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiAuthSignInRoute: typeof ApiAuthSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/storage': {
      id: '/_authenticated/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof AuthenticatedStorageRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/snippets': {
      id: '/_authenticated/snippets'
      path: '/snippets'
      fullPath: '/snippets'
      preLoaderRoute: typeof AuthenticatedSnippetsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/auth/sign-in': {
      id: '/api/auth/sign-in'
      path: '/api/auth/sign-in'
      fullPath: '/api/auth/sign-in'
      preLoaderRoute: typeof ApiAuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSnippetsRoute: typeof AuthenticatedSnippetsRoute
  AuthenticatedStorageRoute: typeof AuthenticatedStorageRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSnippetsRoute: AuthenticatedSnippetsRoute,
  AuthenticatedStorageRoute: AuthenticatedStorageRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiAuthSignInRoute: ApiAuthSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
